language: ruby
rvm:
  - 2.6.3

script: ./script/cibuild

branches:
  only:
  - master     # test the master branch
  - gh-pages

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

addons:
  apt:
    packages:
    - libcurl4-openssl-dev

cache: bundler # caching bundler gem packages will speed up build

# Optional: disable email notifications about the outcome of your builds
notifications:
  email: false

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: _site
  github_token: $GITHUB_TOKEN
  on:
    repo: LuisaoStuff/blog
    on:
      branch: gh-pages
  fqdn: blog.luisvazquezalejo.es
