# Site settings
title: Luis Vázquez Alejo
description: Administrador de sistemas informáticos
baseurl: "" # the subpath of your site, e.g. /blog
url: ""

# User settings
username: Luis Vázquez Alejo
user_description: Administrador de Sistemas Informáticos en Red
user_title: Técnico Superior ASIR
email: mail@luisvazquezalejo.es
#twitter_username: lorem_ipsum
github_username:  luisaostuff
#gplus_username:  lorem_ipsum
#disqus_username: lorem_ipsum
paypal_username: luisaostuff

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Inicio
    url: /
  - title: Categorías
    url: /categorias
  - title: Tags
    url: /tags
  - title: Sobre mí
    url: /sobre-mi

# exclude my node related stuff
exclude: [vendor,'README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png','package.json', 'src', 'node_modules']

