# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "debian/buster64"
  
  config.vm.define :servidor do |servidor|
    servidor.vm.box = "debian/buster64"
    servidor.vm.hostname = "servidor"
    servidor.vm.network "public_network", 
		use_dhcp_assigned_default_route: true ,
		bridge:"eno1"
    servidor.vm.network "private_network",
                ip: "192.168.100.10",
                virtualbox__intnet: "Intranet"
    servidor.vm.provision "shell", inline: <<-SHELL
	apt update
	apt install -y openvpn
    SHELL
    servidor.vm.provision "shell", run: "always", inline: <<-SHELL
	sysctl -w net.ipv4.ip_forward=1
    SHELL
  end
  config.vm.define :cliente do |cliente|
    cliente.vm.box = "debian/buster64"
    cliente.vm.hostname = "cliente"
    cliente.vm.network "private_network",
                ip: "192.168.100.20",
                virtualbox__intnet: "Intranet"
    cliente.vm.provision "shell", run: "always", inline: <<-SHELL
	apt update
	ip r del default
	ip r add default via 192.168.100.10 dev eth1
    SHELL
  end
end
