# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.box = "debian/buster64"
  
  config.vm.define :cliente do |cliente|
    cliente.vm.box = "debian/buster64"
    cliente.vm.hostname = "cliente"
    cliente.vm.network "public_network", 
		use_dhcp_assigned_default_route: true ,
		bridge:"eno1"
    cliente.vm.provision "shell", inline: <<-SHELL
	apt update
	apt install -y openvpn
    SHELL
  end
end
